# Etapa de build
FROM node:18-alpine AS build

WORKDIR /app

COPY package.json pnpm-lock.yaml ./
RUN npm install -g pnpm && pnpm install

COPY . .
RUN npm run build

# Etapa final
FROM node:18-alpine

WORKDIR /app

COPY --from=build /app ./

ENV NODE_ENV production

EXPOSE 3001

CMD ["npm", "start"]
